node{
    def WORKSPACE = "/var/jenkins_home/workspace/BE_SpringBoot_Famil-link/BE/Spring/"
    def dockerImageTag = "springboot-deploy${env.BUILD_NUMBER}"

    try{
        stage('Clone Repo'){
            git url: 'https://lab.ssafy.com/s08-webmobile2-sub2/S08P12A208.git',
                credentialsId: 'jenkins',
                branch: 'master'
        }

        stage('Build docker'){
            dockerImage = docker.build("/var/jenkins_home/workspace/BE_SpringBoot_Famil-link/springboot-deploy:${env.BUILD_NUMBER}")
        }

        stage('Deploy docker'){
            echo "Docker Image Tag Name: ${dockerImageTag}"
            sh "docker stop springboot-deploy || true && docker rm springboot-deploy || true"
            sh "docker run --name springboot-deploy -d -p 3000:9999 springboot-deploy:${env.BUILD_NUMBER}"
        }
    }catch(e){
        throw e
    }
}